global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hadoop-jmx'
    static_configs:
      - targets: ['namenode:9000', 'datanode1:9864', 'datanode2:9865']